<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Alert Historical Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; margin-bottom: 20px; }
        .header { text-align: center; }
        .logo { width: 120px; }
        .title { font-size: 18px; font-weight: bold; }
        .subtitle { font-size: 14px; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #000; padding: 6px; text-align: center; }
        th { background-color: #f2f2f2; }
        .badge { padding: 2px 8px; border-radius: 4px; font-weight: bold; font-size: 11px; }
        .badge-red { background-color: #fee2e2; color: #dc2626; }
        .badge-blue { background-color: #dbeafe; color: #2563eb; }
        .badge-white { background-color: #f3f4f6; color: #374151; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; text-align: center; padding-left: 10px; }
        .page-number:after { content: counter(page); }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('x-stream-logo-with-name.png') }}" class="logo">
        <div class="title">River Monitoring System</div>
        <div class="subtitle">Alert Historical Report</div>
        <div>From: {{ $fromFormatted }} | To: {{ $toFormatted }}</div>
        <div>Generated Date: {{ $generatedDate }}</div>
        <div>Barangay: {{ $barangayName }}</div>
    </div>

    <hr>

    <h4>Alert Summary</h4>
    <table>
        <tr>
            <th>Total Alerts</th>
            <th>Red Alerts</th>
            <th>Blue Alerts</th>
            <th>White Alerts</th>
        </tr>
        <tr>
            <td>{{ $totalAlerts }}</td>
            <td>{{ $redAlerts }}</td>
            <td>{{ $blueAlerts }}</td>
            <td>{{ $whiteAlerts }}</td>
        </tr>
    </table>

    <br>

    <h4>Alert Data Table</h4>
    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Date/Time</th>
                <th>Sensor Type</th>
                <th>Alert Level</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach($alerts as $index => $alert)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ \Carbon\Carbon::parse($alert->recorded_at)->format('M d Y - h:i A') }}</td>
                <td>{{ $alert->sensor_type }}</td>
                <td>
                    <span class="badge badge-{{ strtolower($alert->alert_level) }}">
                        {{ $alert->alert_level }}
                    </span>
                </td>
                <td style="text-align: left;">{{ $alert->description }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <span>Generated by: {{ $generatedBy }}</span> &nbsp;|&nbsp;
        <span class="footer-right">Page <span class="page-number"></span></span>
    </div>
</body>
</html>