<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>BME280 Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin-bottom: 20px;
        }

        .header {
            text-align: center;
        }

        .logo {
            width: 120px;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
        }

        .subtitle {
            font-size: 14px;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 6px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }

        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            font-size: 10px;
            text-align: center;
            padding-left: 10px;
        }

        .page-number:after {
            content: counter(page);
        }
    </style>
</head>

<body>
    <div class="header">
        <img src="{{ public_path('x-stream-logo-with-name.png') }}" class="logo">
        <div class="title">River Monitoring System</div>
        <div class="subtitle">BME280 Sensor Report</div>
        <div>From: {{ $fromFormatted }} | To: {{ $toFormatted }}</div>
        <div>Generated Date: {{ $generatedDate }}</div>
        <div>Buoy Code: {{ $buoyCode }}</div>
    </div>
    <hr>

    <h4>BME280 Sensor Trend</h4>
    @if($chartBase64)
    <div style="width: 693px; margin-bottom: 5px; border: 1px solid #000; padding: 5px;">
        <img src="{{ $chartBase64 }}" width="100%" style="display: block; margin: 0 auto;">
    </div>
    @else
    <p style="color:red;">Chart could not be generated.</p>
    @endif

    <h4>BME280 Sensor Data Table</h4>
    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Temperature (°C)</th>
                <th>Humidity (%)</th>
                <th>Pressure (hPa)</th>
                <th>Recorded At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($readings as $index => $reading)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $reading->temperature_celsius }}</td>
                <td>{{ $reading->humidity }}</td>
                <td>{{ $reading->pressure_hpa }}</td>
                <td>{{ \Carbon\Carbon::parse($reading->recorded_at)->format('F d Y - h:i A') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <span>Generated by: {{ $generatedBy }}</span> &nbsp;|&nbsp;
        <span class="footer-right"> Page <span class="page-number"></span> </span>
    </div>
</body>

</html>
